<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ApiKey>
 */
class ApiKeyFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'user_id' => \App\Models\User::factory(),
            'name' => fake()->words(3, true),
            'key' => null, // Will be auto-generated by model
            'permissions' => ['read', 'write'],
            'rate_limits' => [
                'requests_per_minute' => 60,
                'requests_per_hour' => 1000,
            ],
            'expires_at' => fake()->optional()->dateTimeBetween('now', '+1 year'),
            'last_used_at' => null,
            'is_active' => true,
        ];
    }
}
